### ISSUE TITLE
can it support build from source under ubuntu

### ISSUE THREAD

**Issue by kunlina** [Arthapz/xmake-project-manager#3]
1. my system env is:
[19:18:07 0] ~/work/QT_CREATOR/xmake-project-manager $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
[19:18:09 0] ~/work/QT_CREATOR/xmake-project-manager $ uname -a
Linux knd-OptiPlex-3046 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Arthapz** [comment]
Hey, what is your QtCreator version ? building on Ubuntu from source should be working, but you need to use QtCreator and Qt from official QtSDK until your distribution ship Qt 6.2 and QtCreator 6 in his package manager
